baseurl = "http://grapefilms.pro/"
languageCode = "ru-RU"
title = "Grapefilms production"
uglyurls = true

[params]
	description = "Видеопроизводство. Видеопродакшн. Съёмка корпоративных фильмов, рекламных роликов и музыкальных клипов."
	keywords = ["видеопроизводство", "видеопродакшн", "создание презентационных фильмов", "изготовление роликов", "создание рекламных роликов"]

[taxonomies]
   series = "series"
   
[[menu.main]]
	name = "Главная"
	url = "/"
	weight = 20
[[menu.main]]
	name = "О нас"
	url = "/about.html"
	weight = 30
[[menu.main]]
	name = "Портфолио"
	url = "/portfolio.html"
	weight = 40
[[menu.main]]
	name = "Услуги"
  	url = "/services.html"
  	weight = 50
[[menu.main]]
	name = "Отзывы"
	url = "/mentions.html"
	weight = 60
[[menu.main]]
	name = "Блог"
  	url = "/blog.html"
  	weight = 70
[[menu.main]]
	name = "Контакты"
  	url = "/contacts.html"
  	weight = 80